{
 "title": "RGW Instance Detail",
 "tags": [ "overview" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "rgw_servers",
    "query": "label_values(ceph_rgw_req, ceph_daemon)"
   }
  ]
 },
 "panels": [
  { "title": "RGW Host Detail : $rgw_servers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$rgw_servers GET/PUT Latencies",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (ceph_daemon) (rate(ceph_rgw_get_initial_lat_sum{ceph_daemon=~\"($rgw_servers)\"}[30s]) / rate(ceph_rgw_get_initial_lat_count{ceph_daemon=~\"($rgw_servers)\"}[30s]))",
     "legendFormat": "GET {{ceph_daemon}}"
    },
    {
     "expr": "sum by (ceph_daemon)(rate(ceph_rgw_put_initial_lat_sum{ceph_daemon=~\"($rgw_servers)\"}[30s]) / rate(ceph_rgw_put_initial_lat_count{ceph_daemon=~\"($rgw_servers)\"}[30s]))",
     "legendFormat": "PUT {{ceph_daemon}}"
    }
   ]
  },
  {
   "title": "Bandwidth by HTTP Operation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(ceph_rgw_get_b{ceph_daemon=~\"[[rgw_servers]]\"}[30s])",
     "legendFormat": "GETs {{ceph_daemon}}"
    },
    {
     "expr": "rate(ceph_rgw_put_b{ceph_daemon=~\"[[rgw_servers]]\"}[30s])",
     "legendFormat": "PUTs {{ceph_daemon}}"
    }
   ]
  },
  {
   "title": "HTTP Request Breakdown",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 13, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ceph_rgw_failed_req{ceph_daemon=~\"[[rgw_servers]]\"}[30s])",
     "legendFormat": "Requests Failed {{ceph_daemon}}"
    },
    {
     "expr": "rate(ceph_rgw_get{ceph_daemon=~\"[[rgw_servers]]\"}[30s])",
     "legendFormat": "GETs {{ceph_daemon}}"
    },
    {
     "expr": "rate(ceph_rgw_put{ceph_daemon=~\"[[rgw_servers]]\"}[30s])",
     "legendFormat": "PUTs {{ceph_daemon}}"
    },
    {
     "expr": "rate(ceph_rgw_req{ceph_daemon=~\"[[rgw_servers]]\"}[30s]) -\n  (rate(ceph_rgw_get{ceph_daemon=~\"[[rgw_servers]]\"}[30s]) +\n   rate(ceph_rgw_put{ceph_daemon=~\"[[rgw_servers]]\"}[30s]))",
     "legendFormat": "Other {{ceph_daemon}}"
    }
   ]
  },
  {
   "title": "Workload Breakdown",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(ceph_rgw_failed_req{ceph_daemon=~\"[[rgw_servers]]\"}[30s])",
     "legendFormat": "Failures {{ceph_daemon}}"
    },
    {
     "expr": "rate(ceph_rgw_get{ceph_daemon=~\"[[rgw_servers]]\"}[30s])",
     "legendFormat": "GETs {{ceph_daemon}}"
    },
    {
     "expr": "rate(ceph_rgw_put{ceph_daemon=~\"[[rgw_servers]]\"}[30s])",
     "legendFormat": "PUTs {{ceph_daemon}}"
    },
    {
     "expr": "rate(ceph_rgw_req{ceph_daemon=~\"[[rgw_servers]]\"}[30s]) -\n  (rate(ceph_rgw_get{ceph_daemon=~\"[[rgw_servers]]\"}[30s]) +\n   rate(ceph_rgw_put{ceph_daemon=~\"[[rgw_servers]]\"}[30s]))",
     "legendFormat": "Other (DELETE,LIST) {{ceph_daemon}}"
    }
   ]
  }
 ]
}